# Generated by Django 4.1.7 on 2023-07-15 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Sl_No', models.CharField(max_length=10)),
                ('Description_of_Item', models.CharField(max_length=100)),
                ('Location', models.CharField(max_length=100)),
                ('added_date', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
